### ISSUE TITLE
ht<-alist is inconsistent with ht<-plist in case of duplicate keys

### ISSUE THREAD

**Issue by doublep** [Wilfred/ht.el#11]
First keeps the value associated with the first of equal keys, the second -- with the last. At the very least this should be documented or maybe both should behave in the same way (though this would be a backward-compatibility break).

**Comment by xiongtx** [comment]
`(plist-get '(a 1 b 2 a 3) 'a)` gives `1`, so keeping the first kv-pair instead of last is the right thing to do.
