### ISSUE TITLE
Last non-melpa release was a long time ago

### ISSUE THREAD

**Issue by mdorman** [Wilfred/ht.el#12]
This makes it hard for other packages to accurately state their dependencies---for instance, /kelvinh/orgpage states that it needs ht-1.5 (the last released version), but, in fact, it's not actually compatible.

All that would be required is adding some tags here on github, and melpa-stable would pick the changes up in pretty short order.

**Comment by Wilfred** [comment]
Thanks. I've added tags for 1.6 and 2.0. Let me know if you need tags for other versions too.
