### ISSUE TITLE
Implement a select-keys function like clojure

### ISSUE THREAD

**Issue by garaud** [Wilfred/ht.el#15]
Hi,
I didn't find a function which can return a new has-table from a specific selected keys. You could use this function like:

```lisp
(ht-select-keys table '(:key1 :key2))
```
See also the [select-keys clojure function](https://clojuredocs.org/clojure.core/select-keys)
I've already a draft implementation of a such function. I'll pull request it as soon as possible.

Cheers,
Damien

**Comment by Wilfred** [comment]
Closed in #16.
