### ISSUE TITLE
Nested ht accessor macro?

### ISSUE THREAD

**Issue by alphapapa** [Wilfred/ht.el#17]
Hi there,

Thanks for `ht`, it's very nice to use!  I'm thinking about using it in `pocket-reader`, and so far it's working great in my tests.  I store one global ht with each entry as a ht within it. 

Accessing the hts within the global ht is easy enough, but I was wondering if you would consider adding a macro to ease access to nested hts, similar to how `a` and `kv` do it.  Maybe something like:
```el
(defmacro ht-nested (&rest keys)
  (cl-labels ((rec (keys)
                   `(ht-get ,(if (and (consp (cdr keys))
                                      (cddr keys))
                                 (rec (cdr keys))
                               (cadr keys))
                            ,(car keys))))
    (rec (nreverse keys))))
```
Used like:
```el
(let ((alphabets (ht ("Greek" (ht (1 (ht ('letter "α")
                                         ('name "alpha")))
                                  (2 (ht ('letter "β")
                                         ('name "beta")))))
                     ("English" (ht (1 (ht ('letter "a")
                                           ('name "A")))
                                    (2 (ht ('letter "b")
                                           ('name "B"))))))))
  (ht-nested alphabets "Greek" 1 'letter))  ; => "α"
```
Thanks.

**Comment by Wilfred** [comment]
Supporting nested access seems like a great idea! I'd welcome a PR for this.

I'd be inclined to call this `ht-get*`. Sadly we can't extend `ht-get` to take a series of arguments because the key isn't the last argument.

I think this could be a normal function though, I don't see an obvious benefit of making it a macro.

**Comment by alphapapa** [comment]
Yeah, I looked at extending `ht-get`, but I guess the default argument is important, otherwise there's no way to distinguish unset keys.  I haven't used that feature yet myself, but I'm sure it's useful.

So, something like this?

```el
(defun ht-get* (ht &rest keys)
  (let* ((this-key (car keys))
         (rest-keys (cdr keys))
         (this-value (ht-get ht this-key)))
    (if rest-keys
        (apply #'ht-get* this-value rest-keys)
      this-value)))
```
I guess the macro would avoid some extra function overhead, but I don't know if that would matter.

**Comment by alphapapa** [comment]
I submitted the PR as a function.  The macro might still be worth considering, as legend has it Emacs' function call overhead is high, and doing it as a function adds more function calls.  But you would know much more about that than me, so I'll defer to your judgment.  :)
