### ISSUE TITLE
ht-get as a macro or defsubst?

### ISSUE THREAD

**Issue by alphapapa** [Wilfred/ht.el#19]
Hi again,

Just wondering, since `ht-get` just reorders the arguments to `gethash`, should it be defined as a macro or defsubst to avoid adding an extra function call?  I don't know if it really matters, but e.g. I'm using it in my pocket-reader package, and it runs multiple times for every item in the list, so the overhead does add up (though I haven't profiled it, so I don't know if it's a problem for typical cases).  But since there doesn't seem to be any downside...?

Thanks.

**Comment by Wilfred** [comment]
I'd happy to accept PRs that use `defsubst` :)
