### ISSUE TITLE
define-inline vs defsubst

### ISSUE THREAD

**Issue by Alexander-Miller** [Wilfred/ht.el#33]
The former is a more recent improvement over the latter, offering, among other things, better performance. The downside is that you'd require at least Emacs 25.
I've a PR at the ready if you think this is a worthwhile change.

Here's a comparison benchmark:

```Elisp

(define-inline ht-set-inline! (table key value)
  (inline-quote
   (prog1 nil
     (puthash ,key ,value ,table))))

(define-inline ht-get-inline (table key &optional default)
  (inline-quote
   (gethash ,key ,table ,default)))

(benchmark-run-compiled 10000
  (let ((ht (ht)))
    (dotimes (n 1000)
      (ht-set! ht n n))
    (dotimes (n 1000)
      (ht-get ht n))))

(benchmark-run-compiled 10000
  (let ((ht (ht)))
    (dotimes (n 1000)
      (ht-set-inline! ht n n))
    (dotimes (n 1000)
      (ht-get-inline ht n))))
```
On my system I get a result of 3.45s vs 3.16s, so we're looking at a ~9% improvement. Not the most impressive number, but over in treemacs ht is used in all the important places, so IMO every little bit helps.

**Comment by Wilfred** [comment]
I'd accept a PR for this :)
