### ISSUE TITLE
"context" macro

### ISSUE THREAD

**Issue by neeasade** [Wilfred/ht.el#34]
Hi,

Thanks for this library, I've enjoyed using it for a year or so now. Sometimes it can get a little verbose to make a bunch of ht-get calls or arrange your let or what have you. Using dash.el and s.el, I came up with a macro for single level key resolution. -- here's what I mean by that:

``` elisp
(setq example (ht (:foo "bar")))

(macroexpand-1
  '(ht-with-context
     example
     (concat "nice! " :foo)))

;; => (concat "nice! " (ht-get example :foo))

(ht-with-context
     example
     (concat "nice! " :foo))

;; => "nice! bar"
```

and the macro itself:

``` elisp
(defmacro ht-with-context (table content)
  (-tree-map
    (lambda (tree)
      (-tree-map-nodes (lambda (node) t)
        (lambda (node)
          (if (s-starts-with-p ":" (prin1-to-string node))
            (list 'ht-get table node)
            node))
        tree))
    content))
```

Anyway, just wanted to share -- thanks for the library!~

edit: I'll mention some caveats:

- don't use this if your keys are changing often
- the above doesn't check for the presence of they :key in your ht, so will mess up with other :keys in the form you pass it

**Comment by Wilfred** [comment]
That's really neat! It reminds me of `let-alist` :)
