### ISSUE TITLE
Package cl is deprecated

### ISSUE THREAD

**Issue by mrjbj** [Wilfred/ht.el#37]
```(file-dependents (feature-file 'cl))``` reports this component as depending upon cl which is deprecated 
in favor of ```cl-lib``` in emacs 27 and higher.  If I understand this correctly, the lib "cl" should be replaced with "cl-lib"

**Comment by Wilfred** [comment]
cl is no longer a dependency.

**Comment by mrjbj** [comment]
Thanks!
