### ISSUE TITLE
I cannot install the ht package through melpa

### ISSUE THREAD

**Issue by branduren** [Wilfred/ht.el#8]
I have tried running "M-x package-install <RET> ht <RET>" without any luck, and the package is not listed in package-list-packages.

**Comment by Wilfred** [comment]
Hm, it works for me on a clean Emacs installation. I did:

```
$ mv ~/.emacs.d ~/.emacs.d.backup
$ emacs
```

Then I evaluated the following:

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
```

Then `M-x package-install ht` worked. Could you try this, or suggest how I reproduce your issue?

**Comment by branduren** [comment]
Unfortunately I've changed computer since filing the issue, and I haven't been able to reproduce the issue myself. So I'll close the issue. I also followed your suggestion and it works perfectly - thank you.
