### ISSUE TITLE
ht-set! should return the assigned value

### ISSUE THREAD

**Issue by nonsequitur** [Wilfred/ht.el#9]
To follow the principle of least suprise, `ht-set!` should return the assigned value, like `puthash`, `setq`, `setf`, etc.
I've been bitten a few times by this omission. (And consequently had to replace `ht-set!` with `puthash`.)

**Comment by Wilfred** [comment]
Sorry for the delay on responding.

ht mutation functions all return nil: https://github.com/Wilfred/ht.el#why . I find this less surprising: functions that create a new value return it, but functions that mutate values don't, so you don't end up with multiple variables pointing to the same thing.

That said, `(ht-set! k v)` returning `v` isn't returning a reference to the hash table, so there's less of a risk. I prefer this consistency of all mutation functions returning `nil` though.

I'm open to persuasion: could you give an example where the proposed behaviour would make it nicer?
